# Generated by Django 5.1.1 on 2025-03-04 18:21

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=15)),
                ('jp', models.PositiveIntegerField()),
                ('created_at', models.IntegerField(default=time.time)),
                ('deleted_at', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('type_train', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('img', models.ImageField(upload_to='')),
                ('location', models.TextField(null=True)),
                ('link', models.URLField()),
                ('date', models.IntegerField()),
                ('total_jp', models.PositiveIntegerField()),
                ('is_open', models.BooleanField()),
                ('created_at', models.IntegerField(default=time.time)),
                ('deleted_at', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Uncompleted', 'Uncompleted'), ('Completed', 'Completed')], default='Uncompleted', max_length=15)),
                ('content', models.TextField()),
                ('created_at', models.IntegerField(default=time.time)),
                ('deleted_at', models.IntegerField(default=0)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training'),
        ),
    ]
