# Generated by Django 5.1.1 on 2025-03-06 16:10

import apps.trainings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='date',
            new_name='dateline',
        ),
        migrations.AddField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='type_train_ac',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='img',
            field=models.ImageField(upload_to=apps.trainings.models.file_location),
        ),
        migrations.AlterField(
            model_name='training',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='total_jp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='type_train',
            field=models.CharField(choices=[('Webinar', 'Webinar'), ('Training', 'Training')], default='Training', max_length=10),
        ),
    ]
