# Generated by Django 5.1.1 on 2025-03-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_remove_training_total_jp_alter_section_jp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_open',
        ),
    ]
