# Generated by Django 5.1.1 on 2025-03-07 09:12

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_remove_training_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='dateline',
            field=models.IntegerField(default=time.time),
        ),
    ]
