# Generated by Django 5.1.1 on 2025-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_alter_training_dateline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
