# Generated by Django 5.1.1 on 2025-03-09 03:21

import apps.trainings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_remove_topic_status_alter_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.ImageField(null=True, upload_to=apps.trainings.models.file_location_content),
        ),
    ]
