# Generated by Django 5.1.1 on 2025-03-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_topic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
