# Generated by Django 5.1.1 on 2025-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_training_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
