# Generated by Django 5.1.1 on 2025-03-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_training_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_open',
        ),
    ]
