# Generated by Django 5.1.1 on 2025-03-08 15:32

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0006_remove_topic_status_alter_topic_content'),
        ('users', '0008_alter_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('need action', 'NEED ACTION'), ('progress', 'PROGRESS'), ('time out', 'TIME OUT'), ('completed', 'COMPLETED')], default='need action', max_length=20)),
                ('out_date', models.IntegerField()),
                ('p_learn', models.PositiveIntegerField(default=0)),
                ('S_learn', models.PositiveIntegerField(default=0)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='trainings.training')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
