# Generated by Django 5.1.1 on 2025-03-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='S_learn',
            new_name='s_learn',
        ),
    ]
