# Generated by Django 5.1.1 on 2025-03-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0002_rename_s_learn_enroll_s_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='out_date',
            field=models.IntegerField(default=0),
        ),
    ]
