# Generated by Django 5.1.1 on 2025-03-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0003_alter_enroll_out_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='user_id',
            new_name='user',
        ),
    ]
