# Generated by Django 5.1.1 on 2025-03-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0004_rename_train_id_enroll_train_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='status',
        ),
    ]
