# Generated by Django 5.1.1 on 2025-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0005_remove_enroll_out_date_remove_enroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.CharField(choices=[('need action', 'NEED ACTION'), ('progress', 'PROGRESS'), ('time out', 'TIME OUT'), ('completed', 'COMPLETED')], default='need action', max_length=20),
        ),
    ]
