# Generated by Django 5.1.1 on 2025-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0006_enroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='attandence',
            field=models.BooleanField(default=False),
        ),
    ]
