# Generated by Django 5.1.1 on 2025-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0007_enroll_attandence'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='t_post',
            field=models.BooleanField(default=False),
        ),
    ]
