# Generated by Django 5.1.1 on 2025-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolls', '0008_enroll_t_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='t_karya_nyata',
            field=models.BooleanField(default=False),
        ),
    ]
