# Generated by Django 5.1.1 on 2025-03-08 15:32

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0006_remove_topic_status_alter_topic_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tests', to='trainings.training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('ans', models.TextField()),
                ('user_id', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_training.posttest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
