# Generated by Django 5.1.1 on 2025-03-08 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_training', '0001_initial'),
        ('trainings', '0006_remove_topic_status_alter_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttest',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tests', to='trainings.section'),
            preserve_default=False,
        ),
    ]
