# Generated by Django 5.1.1 on 2025-03-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_training', '0002_posttest_section_id'),
        ('users', '0008_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.user'),
        ),
    ]
