# Generated by Django 5.1.1 on 2025-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_training', '0003_alter_answer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttest',
            name='question',
            field=models.JSONField(null=True, default=dict),
        ),
    ]
