# Generated by Django 5.1.1 on 2025-03-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_training', '0004_alter_posttest_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='post_id',
            new_name='post',
        ),
    ]
