# Generated by Django 5.1.1 on 2025-03-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_training', '0006_alter_answer_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posttest',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='posttest',
            old_name='train_id',
            new_name='train',
        ),
    ]
