# Generated by Django 5.1.1 on 2025-03-08 15:32

import apps.attachment.models
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('cert', models.FileField(upload_to=apps.attachment.models.file_location_certificate)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KaryaNyata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('att', models.FileField(upload_to=apps.attachment.models.file_location_karya_nyata)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('decline', 'DECLINE'), ('accepted', 'ACCEPTED')], default='pending', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
