# Generated by Django 5.1.1 on 2025-03-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('enrolls', '0001_initial'),
        ('users', '0008_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='enroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrolls.enroll'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='users.user'),
        ),
        migrations.AddField(
            model_name='karyanyata',
            name='enroll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyanyata', to='enrolls.enroll'),
        ),
    ]
