# Generated by Django 5.1.1 on 2025-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='enroll_id',
            new_name='enroll',
        ),
        migrations.RenameField(
            model_name='karyanyata',
            old_name='enroll_id',
            new_name='enroll',
        ),
    ]
