# Generated by Django 5.1.1 on 2025-03-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_rename_enroll_id_certificate_enroll_and_more'),
        ('users', '0008_alter_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='karyanyata',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='karyanyata', to='users.user'),
            preserve_default=False,
        ),
    ]
