# Generated by Django 5.1.1 on 2025-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_rename_user_id_certificate_user_karyanyata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert',
            field=models.FileField(upload_to=''),
        ),
    ]
