# Generated by Django 5.1.1 on 2025-03-12 13:41

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0005_alter_certificate_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(default=time.time)),
                ('updated_at', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
