# Generated by Django 5.1.1 on 2025-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nip', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('p_number', models.CharField(max_length=14, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('l_edu', models.CharField(max_length=20, null=True)),
                ('c_school', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
