# Generated by Django 5.1.1 on 2025-03-04 18:21

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.IntegerField(default=time.time),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Head School', 'Headschool')], default='Teacher', max_length=20),
        ),
    ]
