# Generated by Django 5.1.1 on 2025-03-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_img_profile_alter_user_nip_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Head School', 'Headschool'), ('Super User', 'Superuser')], max_length=20),
        ),
    ]
