# Generated by Django 5.1.1 on 2025-03-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Head School', 'Headschool'), ('Super User', 'Superuser')], max_length=20, null=True),
        ),
    ]
