# Generated by Django 5.1.1 on 2025-03-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.IntegerField(default=0),
        ),
    ]
